---
- name: Update All
  hosts: media
  become: true

  tasks:
    - name: Down Compose Projects
      ansible.builtin.shell: |
        docker compose ls -q | xargs -r -I{} docker compose -p "{}" down
      changed_when: true

    - name: Remove unused Docker images
      ansible.builtin.command:
        cmd: docker image prune -f
      register: prune_result
      changed_when: "'Total reclaimed space: 0B' not in prune_result.stdout"

    - name: Find Compose files
      ansible.builtin.find:
        paths: /
        patterns:
          - "compose.y*ml"
          - "docker-compose.y*ml"
        recurse: true
        excludes:
          - "proc"
          - "sys"
          - "dev"
      register: compose_files

    - name: Show Compose files
      ansible.builtin.debug:
        msg: "{{ item.path }}"
      loop: "{{ compose_files.files }}"

    - name: Start Compose projects
      ansible.builtin.shell: |
        cd "{{ item.path | dirname }}"
        docker compose -f "{{ item.path }}" up -d
      loop: "{{ compose_files.files }}"
      loop_control:
        label: "{{ item.path }}"
